### ISSUE TITLE
How to decrease or increase size of contentView? 

### ISSUE THREAD

**Issue by Priyank2016** [dogo/AKSideMenu#10]
Hello,,, Every one

I want to decrease size of Content View which contains menu button .. I have tried all property  but It's not decreased.

Example : 
When i press menu button on  HomeViewController  (e.g. "Left") that  view more decreased and show full menu (e.g just display only menu button of Homeviewcontroller)

**Comment by dogo** [comment]
Hi @Priyank2016 

Could you please me more clear about what you want, I can't understand.

Thanks

**Comment by Priyank2016** [comment]
![simulator screen shot dec 5 2016 11 33 19 am](https://cloud.githubusercontent.com/assets/23315089/20875275/69982088-badf-11e6-91e8-fb46cab25460.png)

Thank you for your quick replay.. 

now, I have attached screen and also write the question in image. I hope you understand well my query.. thanks for your library and i love so much,,

**Comment by dogo** [comment]
Hi @Priyank2016 , 

yep, is possible use the property ```.contentViewScaleValue``` the default value is 0.7

**Comment by Priyank2016** [comment]
Hello @dogo , Thanks for response 

.contentViewScaleValue property change the height of content View but content View show only menu button for close the menu screen.

Menu frame is such as (e.g. 300 if screen width is 320 - width .contentViewScaleValue = 9.0)

menu frame  utilize more UIScreen() width part that show 90% menu and 10% Contentview

**Comment by dogo** [comment]
hum, currently there is no way to achieve what you want. Exists two public attributes to manage the contentView ```.scaleContentView```  and ```.contentViewScaleValue```.

A PR is always welcome :P

**Comment by pvn** [comment]
@dogo Could you please provide a way to reduce the size.

**Comment by Devyani-Tact** [comment]
You can change **.contentViewInPortraitOffsetCenterX** value and it will help to decrease the size of content view and in my case i passed this value to 200 and it hide the content view completely.
