### ISSUE TITLE
Status bar issue

### ISSUE THREAD

**Issue by meszarospeter** [dogo/AKSideMenu#17]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.3.3`
 - Device OS version: `10.1`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1. Set scaleContentView to false
 2. Set menuPrefersStatusBarHidden to true
 3. Show left menu
 4. The status bar doesn't disappear

###### Expected Result
The status bar will disappear by showing the left side menu. If I enable scaleContentView (default it's true) the status bar will hide.

###### Actual Result
The status bar doesn't disappear by showing the left side menu

### Tell us what could be improved:
```
override open var prefersStatusBarHidden: Bool {
        var statusBarHidden: Bool = false

        statusBarHidden = self.visible ? self.menuPrefersStatusBarHidden : self.contentViewController!.prefersStatusBarHidden
        if self.contentViewContainer.frame.origin.y > 10 {
            statusBarHidden = self.menuPrefersStatusBarHidden
        } else {
            statusBarHidden = self.contentViewController!.prefersStatusBarHidden
        }
        return statusBarHidden
    }
```
You should change this if condition: `if self.contentViewContainer.frame.origin.y > 10` to `if self.contentViewContainer.frame.origin.x > 10`.  Also, you should fix this if condition in `override open var preferredStatusBarUpdateAnimation: UIStatusBarAnimation` and `override open var preferredStatusBarStyle: UIStatusBarStyle`

**Comment by dogo** [comment]
Thanks for reporting @meszarospeter, sadly the fix is not so simple. I will fix this this week.

**Comment by dogo** [comment]
@meszarospeter Please update to 1.3.5

**Comment by meszarospeter** [comment]
Thank you. I really appreciate your effort.
