### ISSUE TITLE
Still crashing a little

### ISSUE THREAD

**Issue by CodeReaper** [dogo/AKSideMenu#18]
Hmmm... I have just now noticed you asked me to check the develop branch on #16.

I am seeing code ala:

```
if optional  == nil { return }
// and then using optional! (explicitly unwrapped)
```

... which concerns me a bit. Since I am back here looking at issues because I have had another !-related crash. :)

I am willing to arrange the code to avoid using explicitly unwrapped optionals and use lets and guards instead unless you would rather do it yourself or do something different to avoid crashing. What do you think?

**Comment by dogo** [comment]
Hi @CodeReaper , It will be nice a PR removing force unwraps. I was trying to spare some time to do this, but you know... time is short =(

**Comment by CodeReaper** [comment]
@dogo Okay expect a PR soonish...

**Comment by dogo** [comment]
@CodeReaper feel free to close this issue, when you have time to validate you PR

**Comment by CodeReaper** [comment]
@dogo I validated it as best I can, but I am thinking the issue stays open until a new version is published. :)

**Comment by dogo** [comment]
Please update to 1.3.5
