### ISSUE TITLE
How to disable "swipe gesture" on rightViewController?

### ISSUE THREAD

**Issue by exocode** [dogo/AKSideMenu#22]
- [X ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.3.5`
 - Device OS version: `11.0`
 - Device Name: `iPhone 7`
 
###### Reproduction Steps
 1. place TableView rightviewController
 2. add tableViewAction 

```
    func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        return true
    }
    
    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath) {
        if (editingStyle == UITableViewCellEditingStyle.delete) {
            tableView.beginUpdates()
            print("deleting")
            tableView.endUpdates()
            
        }
        
    }

```

 3. start from right to left swiping on tableViewCell. 

###### Expected Result

TableViewCell action should appear

###### Actual Result

 rootViewController appears

### Tell us what could be improved:

property from rightviewController to deactivate swiping

<img width="405" alt="bildschirmfoto 2017-06-26 um 15 27 44" src="https://user-images.githubusercontent.com/1597621/27535059-ce08da66-5a86-11e7-86f7-13b6d83b4342.png">

(based on your Demo App)

**Comment by dogo** [comment]
@exocode 

From AKSideMenu documentation

**Enable or disable right pan gesture recognition. Defaults to True.**
``` swift
public var panGestureRightEnabled: Bool
```

**Comment by exocode** [comment]
I added a "Demo" to make the issue "exploreable":

SImply run the Demo App. Based on your Demo. Only added the Swipe-Functions.
If you point the "Initial ViewController" Arrow to the "RightViewController" you will see, that swipes are working. If you point it back to "RootViewController" the Swipe does not work:

https://github.com/exocode/AKSideMenu

**Comment by dogo** [comment]
Thanks @exocode , I'll take a look at it

**Comment by exocode** [comment]
I found out, that when I put` panGestureEnabled` into the ` class RootViewController : AKSideMenu, AKSideMenuDelegate`

```    
RootViewController : AKSideMenu, AKSideMenuDelegate {
   override public func awakeFromNib() {
        super.awakeFromNib()
        self.panGestureEnabled = false // <-----
    }
}
```

it's working (nearby)!

 It's only working when I put `panGestureEnabled` into `awakeFromNib`. The delegate method of My AKSideMenuDelegate cannot set this value. So I cannot switch to "normal state" where the swipe should open the menu.

Do I have to "refresh" anything?
