### ISSUE TITLE
Unwind segue error

### ISSUE THREAD

**Issue by barankaraoguzzz** [dogo/AKSideMenu#23]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.3.5`
 - Device OS version: `10.3`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 I should use unwind segue in my app or dissmiss viewController.i am using this code for ViewController transition.
`self.sideMenuViewController!.setContentViewController(UINavigationController.init(rootViewController: self.storyboard!.instantiateViewController(withIdentifier: "HighScoreControllerID")), animated: true)
        self.sideMenuViewController!.hideMenuViewController()`

i want to go back with unwind segue. But it is not working. i have tried normal segue then unwind segue is working. Help please

**Comment by jorden0154** [comment]
let myProfileVC = storyboard.instantiateViewController(withIdentifier: "MyProfileViewController") as! MyProfileViewController      
let obj : UINavigationController = self.sideMenuViewController?.contentViewController as! UINavigationController   
obj .pushViewController(myProfileVC, animated: true)
self.sideMenuViewController!.hideMenuViewController()

**Comment by barankaraoguzzz** [comment]
Thank you for answer. it is working :)
