### ISSUE TITLE
App Freezing when using on Xcode and normally crash

### ISSUE THREAD

**Issue by chathuralakmal** [dogo/AKSideMenu#25]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.0.0`
 - Device OS version: `6.0`
 - Device Name: `iPhone 5`
 
###### Reproduction Steps
 1. in my SecondViewController in Menu i have another step to go "Detail Second View Controller"
if i go their and come back and press menu app get freeze. if i unplug from xcode. it works fine. but it get crash when i go and click play with menu fast. i think something to do with GCD

**Comment by chathuralakmal** [comment]
![screenshot 2017-09-03 11 32 03](https://user-images.githubusercontent.com/12609979/30000955-978fb2ca-909b-11e7-8bb4-6fc610013bca.png)
![screenshot 2017-09-03 11 32 09](https://user-images.githubusercontent.com/12609979/30000956-97938b34-909b-11e7-95fb-e5cdfca13c54.png)

**Comment by dogo** [comment]
Please update to 1.3.5

**Comment by chathuralakmal** [comment]
I just found out it happens only when i install google ads sdk in pod. Amd
not for every devices. Just one device i have been testing.ill update and
check

On Sep 4, 2017 22:23, "Diogo Autilio" <notifications@github.com> wrote:

Please update to 1.3.5

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dogo/AKSideMenu/issues/25#issuecomment-327001592>, or mute
the thread
