### ISSUE TITLE
UI blocker

### ISSUE THREAD

**Issue by Yoloabdo** [dogo/AKSideMenu#26]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.0.0`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1. Open my app
 2. Browse through 
 3. App freezes 

###### Expected Result
Normal flow
###### Actual Result
App UI freezing 
### Tell us what could be improved:
I debugged the view and found a uibutton laying on my whole UI window as has been added from nowhere, I didn’t have this issue before using the pod, so I think it’s somehow added wrongly

**Comment by Yoloabdo** [comment]
- [ yes] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.0.0`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1. Open my app
 2. Browse through 
 3. App freezes 

###### Expected Result
Normal flow
###### Actual Result
App UI freezing 
### Tell us what could be improved:
I debugged the view and found a uibutton laying on my whole UI window as has been added from nowhere, I didn’t have this issue before using the pod, so I think it’s somehow added wrongly

**Comment by dogo** [comment]
Could you please provide me more information about it ? I could not reproduce the issue, maybe could you please build a sample for it

**Comment by dogo** [comment]
@Yoloabdo Please again using the develop branch, the MR #33 could be related.
