### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by nsnull0** [dogo/AKSideMenu#27]
###### Include the following:
 - AKSideMenu version: `1.3.5`
 - Device OS version: `11`
 - Device Name: `iPhone X`

### Swift 4 Support:
Please maintenance for swift 4 support,
I could help if you guys want.

**Comment by dogo** [comment]
Working on it :D

**Comment by dogo** [comment]
Please update to 1.4.0

**Comment by nsnull0** [comment]
Perfect! Thank you.
