### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by Euphrates-Media** [dogo/AKSideMenu#3]
Hi
When will you update to Swift 3?

**Comment by dogo** [comment]
Yep! @Euphrates-Media, please take a look on https://github.com/dogo/AKSideMenu/tree/feature/swift3 branch

**Comment by dogo** [comment]
@Euphrates-Media please update to version 1.2

**Comment by Euphrates-Media** [comment]
Thanks !

A.V.Ebrahimi
vakilzadeh@gmail.com
