### ISSUE TITLE
ContentViewContainer invisible after rotation

### ISSUE THREAD

**Issue by calli23** [dogo/AKSideMenu#31]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.4.0`
 - Device OS version: `11.1`
 - Device Name: `iPhone 7`
 
###### Reproduction Steps
 1. Open app in landscape mode.
 2. Make your app show left menu.
 3. now rotate to portrait mode.

###### Expected Result
The ContentViewContainer should be visible on the right side.
###### Actual Result
It looks like the ContentViewContainer is rotating out of the right bound of the screen. All steps can be repeated as often as you want to reproduce this issue.
### Tell us what could be improved:
Is there a way to fix that?

**Comment by dogo** [comment]
@calli23 
humm that's weird, I tested were and seems fine

https://www.dropbox.com/s/r37t51xsv29w5gn/Sem%20T%C3%ADtulo.mov?dl=0

**Comment by calli23** [comment]
I'm actually using the storyboard solution.

[https://1drv.ms/v/s!AinWFbAKlwAgiysWWCLj0FveEXhC](url)

This was made with an iPhone X but the same effect can be observed with an iPhone 7. I think it does not rely on the device.

**Comment by calli23** [comment]
Lesson learned:
Don't use methods in RootViewController that may overwrite one from AKSideMenu class. I used to define viewWillTransitionToSize() in RootViewController which completely overwrote the standard behavior defined in AKSideMenus method willAnimateRotation().
