### ISSUE TITLE
 interactivePopGestureRecognizerEnabled - Make Disable

### ISSUE THREAD

**Issue by KushThakkar** [dogo/AKSideMenu#37]
Hello,

I want to disable  interactivePopGestureRecognizer.

**Comment by dogo** [comment]
Hi @KushThakkar, please next time open an issue with the TEMPLATE ISSUE filled.

To turn off the `interactivePopGestureRecognizer`  set the AKSideMenu property to `interactivePopGestureRecognizerEnabled` to false
