### ISSUE TITLE
how to support arabaic language?

### ISSUE THREAD

**Issue by muthusabarinathan** [dogo/AKSideMenu#38]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.0.0`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1.
 2.
 3.

**Comment by dogo** [comment]
Please fill out the issue template. Feel free to reopen
