### ISSUE TITLE
Unexpectedly found nil

### ISSUE THREAD

**Issue by furkankadioglu** [dogo/AKSideMenu#39]
- AKSideMenu version: 1.4.1
 - Device OS version: Latest
 - Device Name: `iPhone X`
 
###### Reproduction Steps
 1. Imported AKSideMenu pod and installed
 2. Imported Chart pod and installed
 3. Trying to add a chart to my view controller OR trying to add a button with background image.
 4. Crash.

###### Actual Result
Result and crash: http://i.hizliresim.com/BLPoRM.png
Code screen: http://i.hizliresim.com/4arYZ7.png

**Comment by dogo** [comment]
@furkankadioglu Could you please provide me a sample? Or compare you code with the Storyboard sample

**Comment by furkankadioglu** [comment]
@dogo Hello dogo, thank you for fastest reply. 

Here is my project source: https://ufile.io/tx23p (without pods)

**Comment by furkankadioglu** [comment]
@dogo Did you examine?

**Comment by dogo** [comment]
Downloading now

**Comment by dogo** [comment]
@furkankadioglu 

https://www.dropbox.com/s/c3v2m6ijvtk0wfd/Untitled.mov?dl=0

Please watch my video.

**Comment by furkankadioglu** [comment]
@dogo Hi again,

Thank you for recording a video. You're awesome. But it is not nil, you are looking ViewController. Button is in the first controller. (There is have IBOutlet weak var). No problem forget it. 

I think you're looking wrong controller. Button is here:
![screen shot 2018-02-01 at 01 02 50](https://user-images.githubusercontent.com/5060068/35649987-b8e3ee52-06eb-11e8-8f56-55dd8fd38f13.png)

If you use telegram: **TheRys**

**Comment by furkankadioglu** [comment]
@dogo There is another example with [Chart](https://github.com/danielgindi/Charts)


This is working (without AKSideMenu)
![screen shot 2018-02-01 at 01 13 09](https://user-images.githubusercontent.com/5060068/35650436-236a2f92-06ed-11e8-88bd-0b12642149bb.png)

This is not working (with AKSideMenu / Same code)
 - Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value
![screen shot 2018-02-01 at 01 14 44](https://user-images.githubusercontent.com/5060068/35650491-52273e74-06ed-11e8-8a28-f4ce7fb713d4.png)

Files: [https://ufile.io/rvnzm](Download)

**Comment by furkankadioglu** [comment]
Waiting your reply and thank you for huge support @dogo

**Comment by dogo** [comment]
Seems fine too but I had to make the touchUpInside link


https://www.dropbox.com/s/1x401nztos8ph76/Untitled2.mov?dl=0

**Comment by furkankadioglu** [comment]
@dogo Did you examine last files and screenshots?

**Comment by furkankadioglu** [comment]
Waiting for reply @dogo 🥇

**Comment by furkankadioglu** [comment]
Still waiting for any solution.. @dogo

**Comment by AlexandrPonomarev** [comment]
@furkankadioglu Your crash is not related to the side menu of AksideMen. Understand your code and problems in it yourself.

**Comment by dogo** [comment]
Indeed is not a AKSideMenu issue. Sorry @furkankadioglu
