### ISSUE TITLE
how to call side menu over the context..?

### ISSUE THREAD

**Issue by afsalkp123** [dogo/AKSideMenu#40]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.0.0`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1.
 2.
 3.

**Comment by dogo** [comment]
Please provide information filling the issue template
