### ISSUE TITLE
Shadow is not visible 

### ISSUE THREAD

**Issue by vishalpethani** [dogo/AKSideMenu#42]
![simulator screen shot - iphone 8 - 2018-04-25 at 19 49 50](https://user-images.githubusercontent.com/22548020/39251963-30e77352-48c2-11e8-82ec-a57243a4e0c1.png)

shadow is not visible

I also write the following code in RootViewController

        
        self.contentViewShadowColor = .black
        self.contentViewShadowOffset = CGSize(width: 2, height: 2)
        self.contentViewShadowOpacity = 0.6
        self.contentViewShadowRadius = 12
        self.contentViewShadowEnabled = true
        self.backgroundImage = nil

could anyone help me to bring out me from this issue?

**Comment by shaikh1110** [comment]
Hey Devs, even i am facing this issue... no matter what... i spent so many hours but couldn't achieve to get shadow on center view... So i made a work around on sideview controllers to show a shadow layer but its not the same as having for original

`override func viewDidAppear(_ animated: Bool) {
        let sL = CALayer()
        sL.frame = CGRect(x: 0, y: 26, width: 46, height: uiSize.height - 52)
        sL.borderColor = UIColor.clear.cgColor
        sL.borderWidth = 1
        sL.shadowRadius = 15
        sL.shadowOpacity = 0.25
        sL.masksToBounds = false
        sL.shadowPath = UIBezierPath(rect: sL.bounds).cgPath
        self.view.layer.addSublayer(sL)
    }`

**Comment by PaulEhrhardt** [comment]
+1 
I also have this issue.

**Comment by dogo** [comment]
Testing the version 1.4.2 I realised, the contentView shadow is working as expected

![simulator screen shot - iphone x - 2018-09-25 at 21 45 58](https://user-images.githubusercontent.com/1487375/46050864-ca252380-c10c-11e8-97bd-6fa2b7795378.png)
![simulator screen shot - iphone x - 2018-09-25 at 21 46 00](https://user-images.githubusercontent.com/1487375/46050866-ca252380-c10c-11e8-8aab-fb83f40d2f4b.png)


ps. I removed the background to make more visible

**Comment by vishalpethani** [comment]
@PaulEhrhardt is right...The shadow is clipped at the bounds of view. That's why we couldn't get the result as expected.

**Comment by fadizant** [comment]
`self.contentViewContainer.clipsToBounds = false`
will fix it

**Comment by dogo** [comment]
@vishalpethani @shaikh1110 @PaulEhrhardt @fadizant 
Please test the develop branch, should be fixed. Sorry for taking so long

**Comment by fadizant** [comment]
> @vishalpethani @shaikh1110 @PaulEhrhardt @fadizant
> Please test the develop branch, should be fixed. Sorry for taking so long

it's work fine in develop branch
thanks
