### ISSUE TITLE
Image on BackgroundImageView is not showing up

### ISSUE THREAD

**Issue by PaulEhrhardt** [dogo/AKSideMenu#44]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.4.1`
 - Device OS version: `12.0`
 - Device Name: `iPhone 7`
 
###### Reproduction Steps
 1. Setup AKSidemenu
 2. Assign an image to the `backgroundImage` property
 3. Background image does not show up 

###### Expected Result
Image should be visible.

###### Actual Result

<img width="570" alt="screen shot 2018-09-23 at 12 36 37" src="https://user-images.githubusercontent.com/5812406/45927099-02224000-bf2e-11e8-9811-3fd50e9aed2a.png">

**Comment by dogo** [comment]
Thats weird @PaulEhrhardt , seems fine here with storyboard and without

![simulator screen shot - iphone x - 2018-09-25 at 21 50 09](https://user-images.githubusercontent.com/1487375/46050913-15d7cd00-c10d-11e8-8b20-e31a7d13f756.png)

**Comment by PaulEhrhardt** [comment]
Thank you i will do and test it out.

**Comment by PaulEhrhardt** [comment]
Same issue using https://github.com/dogo/AKSideMenu/releases/tag/1.4.2

My `MainViewController` derives from AKSideMenu. When i set the background image inside the overridden `viewDidLoad` it does not show up.

However if i set the backgroundImage property directly on startup in my AppDelegate like in the examples it shows up.

**Comment by dogo** [comment]
@PaulEhrhardt Try to set the background image on awakeFromNib() like: `self.backgroundImage = UIImage(named: "Stars")`

**Comment by PaulEhrhardt** [comment]
Thank you for your help. I do not use Storyboards in my project but i got it running by setting it in the app delegate anyway so i can close this issue now.
