### ISSUE TITLE
Manage corner spaces.

### ISSUE THREAD

**Issue by Nitinbond** [dogo/AKSideMenu#45]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.0.0`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1.
 2.
 3.

### Tell us what could be improved:
Getting corner spaces in content view controller [
![screenshot 2018-09-28 at 11 20 10 am](https://user-images.githubusercontent.com/11436995/46190393-fe693180-c310-11e8-91f6-3f795571922b.png)
](url)

**Comment by dogo** [comment]
The content view corner radius. Defaults to 0.

`public var contentViewCornerRadius: CGFloat`

**Comment by Z1Z0** [comment]
`public var contentViewCornerRadius: CGFloat`
@dogo I searched for it but I didn't find it.

**Comment by dogo** [comment]
contentViewCornerRadius has been removed, due to many issues. Sorry

**Comment by Z1Z0** [comment]
> contentViewCornerRadius has been removed, due to many issues. Sorry

Ok, Thank you.
