### ISSUE TITLE
Content view shadow effect.....

### ISSUE THREAD

**Issue by balkrishanyadav** [dogo/AKSideMenu#46]
Hello, I am using  AKSideMenu For My App. I have to implement Content view Shadow View In like attached manner.  
![c_users_lenovo_appdata_local_packages_microsoft skypeapp_kzf8qxf38zg5c_localstate_a8eed1c7-408f-4a0f-a4a0-317e6f262c6e](https://user-images.githubusercontent.com/6735695/46286349-7f882900-c59c-11e8-81b1-3ef5cbee0220.png)

Thanks

**Comment by dogo** [comment]
Probably you will need those properties

`public var contentViewShadowOffset: CGSize`
Defaults to CGSizeZero.

`public var contentViewShadowOpacity: Float`
Defaults to 0.4.

`public var contentViewScaleValue: CGFloat`
Defaults to 0.7.

**Comment by balkrishanyadav** [comment]
Thanks Dogo,
 But I have to implement in different manner like below attached image in red color rectangle.
![46286349-7f882900-c59c-11e8-81b1-3ef5cbee0220](https://user-images.githubusercontent.com/6735695/46461930-a1bcb980-c7dd-11e8-8455-931cbe7c0991.png)

**Comment by dogo** [comment]
Please @balkrishanyadav test the develop branch, should be fixed. Sorry for taking so long
