### ISSUE TITLE
Calling variable sideMenuViewController in UIViewController extension freezes the app when it is not in view heirarchy

### ISSUE THREAD

**Issue by gauravlnx** [dogo/AKSideMenu#47]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

If in a viewController I access the defined in the UIViewController extension, the app freezes
```
self.sidemenuViewController
```
This happens if the side menu is not in the view Heirarchy. The app goes into an infinite loop and app freezes.

###### Include the following:
 - AKSideMenu version: `1.0.0`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1. Load SideMenu inside a Navigation stack
 2. Instead of pushing a controller from the inside of the side menu, push it directly to the above navigation controller.
 3. In the controller, if the sidemenuViewController property is accessed, the app will freeze.

###### Expected Result
The property should return nil instead of going into an infinite while loop.

###### Actual Result
The app goes into an infinite while loop.

**Comment by dogo** [comment]
Please provide me a sample

**Comment by dogo** [comment]
@hackiftekhar
Please update to 1.4.5
