### ISSUE TITLE
Instance member 'autoresizingMask' cannot be used on type 'UIView'

### ISSUE THREAD

**Issue by Premal-Khetani** [dogo/AKSideMenu#48]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.0.0`
 - Device OS version: `11.4`
 - Device Name: `iPhone 8 Plus`
 
###### Reproduction Steps
 1. Build the project. 

###### Expected Result
successfully build.
###### Actual Result
not able to build the project. 
### Tell us what could be improved:
can you please solve it.

![screen shot 2018-10-29 at 12 23 27 am](https://user-images.githubusercontent.com/13691970/47620544-28c92d00-db11-11e8-9375-8e359edca139.png)

**Comment by dogo** [comment]
Xcode version?

**Comment by Premal-Khetani** [comment]
@dogo  xcode 9.4

**Comment by dogo** [comment]
Update to Xcode 10
