### ISSUE TITLE
How to use only left view controller

### ISSUE THREAD

**Issue by ssuhanov** [dogo/AKSideMenu#5]
Hi, I want to use AKSideMenu only at the left side (there is burger menu in my application), but the empty right view controller still showing when I slide from right side to left. How can I turn off the right view controller? Thanks.

**Comment by ssuhanov** [comment]
Sorry, I have found solution. Just add ```self.panGestureRightEnabled = false``` to the RootViewController. :)

**Comment by Alex293** [comment]
I would be nice to be able to use only one menu because we have to instantiate one useless view controller. When you open the left one you try to close the right one and if it doesn't exit it crash.
ou should use rigthVC?.close()
Tho great work here !!
