### ISSUE TITLE
Sidemenu stuck in swipe

### ISSUE THREAD

**Issue by fadizant** [dogo/AKSideMenu#50]
- [ ✔️] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.4.2`
 - Device OS version: `12.0`
 - Device Name: `iPhone 6s`
 
###### Reproduction Steps
 1. add sidemenu using pod
 2. using storyboard like sample
 3. add rightmenu only

###### Expected Result
swipe and release before fully open must be close or open side menu
###### Actual Result
menu stuck in the middle of swiping 
### Tell us what could be improved:
make sidemenu full open or close depends of percentage of swipe to full open 

![img_1002](https://user-images.githubusercontent.com/13743626/50394930-8ec8de00-0769-11e9-915a-6c05090bd673.jpg)

**Comment by fadizant** [comment]
after double check, I found that if you don't set leftMenuViewController the swipe back will not work fine, any suggest to fix this issue 

Thanks

**Comment by fadizant** [comment]
here is the problem 

    func hideMenuViewControllerAnimated(_ animated: Bool) {
            let rightMenuVisible: Bool = self.rightMenuVisible
    
            if let visibleMenuViewController = (rightMenuVisible ? self.rightMenuViewController : self.leftMenuViewController) {
    .....

I use the **rightMenuViewController** only so when i try to slide the menu with and release it in blow of open limit the AKSideMenu will try to hide the menu but the case is **self.rightMenuVisible** is false and the  **self.leftMenuViewController** is nil so the hide function will not work in this case.

**Comment by nihasmata** [comment]
I have the same issue ,I am using only rightMenuViewController. When i disable leftMenuViewController like below swipe is not working correctly. When i release my finger near to safe area, swipe freezes.

 self.contentViewController = storyboard.instantiateViewController(withIdentifier: "contentViewController")
            //self.leftMenuViewController = storyboard.instantiateViewController(withIdentifier: "leftMenuViewController")
            self.rightMenuViewController = storyboard.instantiateViewController(withIdentifier: "rightMenuViewController")

**Comment by dogo** [comment]
Thanks guys! Fixed 
@fadizant 
@nihasmata
