### ISSUE TITLE
Memory not manage on Navigation from leftview controller

### ISSUE THREAD

**Issue by sazidmsi** [dogo/AKSideMenu#51]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.0.0`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1.  Just try to tap on menu icon and select an item from table 
 2. Check the memory for the debug navigator pane in left hand side.
 3. If you repeat this step, memory increase to 1 gb and app got crashed

###### Expected Result
Memory should be manage itself

###### Actual Result
Memory increase unexpectedly while we have used side menu for navigation 
### Tell us what could be improved:

You should provide the array of content vc in side menu controller

**Comment by dogo** [comment]
@sazidmsi 
Could not reproduce, tested with Simple App example and the memory consumption remained at 57.4 ~ 57,7
<img width="270" alt="screen shot 2019-01-08 at 00 01 45" src="https://user-images.githubusercontent.com/1487375/50807329-add27e80-12d8-11e9-8038-3c87aa6f2def.png">

Could you please provide me more information about the issue?
