### ISSUE TITLE
How to apply corner radius with shadow to content view. Please advice?

### ISSUE THREAD

**Issue by harjotsingh007** [dogo/AKSideMenu#52]
Hi, i just want to know how can i achieve shadow and corner radius at same time in the contentviewcontroller. I tried to play with the values you have tried, still not able to achieve what i actually want.

Thanks for the beautiful library.

**Comment by dogo** [comment]
Please fill correctly the issue form

**Comment by harjotsingh007** [comment]
Seriously, i tried to edit it again, first time putting the issue in library, still the issue i think you have understood well, i just want to achieve the corner radius on contenViewcontainer with shadow enabled because i tried either values, i am able to achieve once per time. Like, for example if i want corner radius, shadow is not there, and if i want shadow, corner radius is not there.

**Comment by harjotsingh007** [comment]
Still waiting for the reply.Please give some advise?

**Comment by harjotsingh007** [comment]
Can you please help with my issue with shadow and corner radius, i need it urgent.
