### ISSUE TITLE
Push view controller from leftMenuViewController?

### ISSUE THREAD

**Issue by RNUK** [dogo/AKSideMenu#56]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.3.5`
 - Device OS version: `12.1`
 - Device Name: `iPad Pro`
 
###### Reproduction Steps
 1. Setup as per example
 2. Create button in LeftMenuController to push content 
 3.

Using code: 
```
self.sideMenuViewController!.navigationController?.pushViewController(eventVC, animated: true)
self.sideMenuViewController!.hideMenuViewController()
```

###### Expected Result
Left menu hides and new view is pushed onto navigation stack 

###### Actual Result
Left menu closes

**Comment by keshu1024** [comment]
```
self.sideMenuViewController!.setContentViewController(UINavigationController(rootViewController: YourViewController), animated: true)

self.sideMenuViewController!.hideMenuViewController()
```

**Comment by usamaazam10** [comment]
@RNUK This is how I achieve this functionality

let vc = SomeViewController
        (UIApplication.shared.delegate as? AppDelegate)?.sideMenuViewController?.hideMenuViewController()
            (((UIApplication.shared.delegate as? AppDelegate)?.sideMenuViewController?.contentViewController) as? UINavigationController)?.pushViewController(vc, animated: true)
