### ISSUE TITLE
ContentViewCornerRadius is available?

### ISSUE THREAD

**Issue by Lailan** [dogo/AKSideMenu#57]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.0.0`
 - Device OS version: `12.1`
 - Device Name: `iPhone X`
 
### Tell us what could be improved:

First, congratulations on this wonderful lib.
I would like to know if there is any possibility of adding a cornerRadius in the contentView.

Thanks

**Comment by Z1Z0** [comment]
@Lailan Have you solve this?

**Comment by dogo** [comment]
As #45, this feature has been removed
