### ISSUE TITLE
Issue with modals

### ISSUE THREAD

**Issue by Alex293** [dogo/AKSideMenu#6]
Hi I use a AKSideMenu controller as my root vc. I have an issue with modals because if I present a modal over it I can't use the SideMenu property and If I the the presenting vc I got the AKSideMenu which don't have a side menu it self.

TL;DR It would be great that the side menu can use it own side menu property !

**Comment by dogo** [comment]
Hi, @Alex293 could you please provide me a sample app ? Thanks
