### ISSUE TITLE
space at top right and left corner of  navigation bar  while using aksidemenu

### ISSUE THREAD

**Issue by jainam1993** [dogo/AKSideMenu#60]
![Screenshot 2019-04-17 at 5 58 18 PM](https://user-images.githubusercontent.com/14103884/56287592-69a61400-613a-11e9-8fe7-6679cc7fc2dd.png)

it seems like there is corner radius or white space at the top of navigation bar , how to remove it ?

**Comment by dogo** [comment]
Dupe

**Comment by jainam1993** [comment]
hi  @dogo ,
