### ISSUE TITLE
didHideMenuViewController is never called

### ISSUE THREAD

**Issue by josipbernat** [dogo/AKSideMenu#62]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.4.3`
 - Device OS version: `All versions`
 - Device Name: `All devices`
 
###### Reproduction Steps
 1. Set some class (such as left menu view controller) as AKSideMenu delegate
 2. Put breakpoint at **func sideMenu(_ sideMenu: AKSideMenu, didHideMenuViewController menuViewController: UIViewController)** and write print("hello world") to have written proof that things aren't working.
 3. Open and hide left menu

###### Expected Result

After hide animation is finished debugger should stop at breakpoint or write in console message that we put inside print() function.

###### Actual Result

**func sideMenu(_ sideMenu: AKSideMenu, willHideMenuViewController menuViewController: UIViewController)** is called twice instead once. Investigating in code I saw that inside AKSideMenu.swift (line 442) **willHideMenuViewController** is called instead of **didHideMenuViewController** inside completion block.

### Tell us what could be improved:

Please call didHideMenuViewController in completion block. If needed I can do thing through pull request.

**Comment by dogo** [comment]
https://github.com/dogo/AKSideMenu/commit/b174c37306a18601a7fdc72640a38d6cfaa6ee08
Its already fixed, but not yet released.

**Comment by dogo** [comment]
Please update to 1.4.4
