### ISSUE TITLE
exception on UIButton Constructor ios 13.1 xcode 11

### ISSUE THREAD

**Issue by boardmain** [dogo/AKSideMenu#67]
- AKSideMenu version: 1.4.4
 - Device OS version: 13.1
 

if i enable Exception Breakpoints in xcode for all type of error
i have many error here

`
@IBDesignable
open class AKSideMenu: UIViewController, UIGestureRecognizerDelegate {

    var visible: Bool = false
    var leftMenuVisible: Bool = false
    var rightMenuVisible: Bool = false
    var sideMenuDelegateNotify: Bool = false
    var originalPoint: CGPoint = .zero
    var contentButton: UIButton = UIButton() <------ HERE
`

i think you can try it in a blank project

**Comment by dogo** [comment]
Could not reproduce
<img width="287" alt="Screen Shot 2019-11-20 at 11 59 08" src="https://user-images.githubusercontent.com/1487375/69249770-32df2300-0b8d-11ea-892f-5e4d2a2bbe92.png">
