### ISSUE TITLE
Improvement to make RightSide Menu as optional

### ISSUE THREAD

**Issue by anandramv** [dogo/AKSideMenu#7]
Can you improvise the code to make right side menu to be optional? At present we have to enter Right side and left Side view controllers while initializing AKSideMenu.

Would be great if we make both as optional.

**Comment by dogo** [comment]
Hi @anandramv could you please take a look on develop branch and tell me if its okay 💃 
Thanks

**Comment by anandramv** [comment]
Looks perfect!!! Thank you! 👍

**Comment by dogo** [comment]
please update to 1.3.0

**Comment by anandramv** [comment]
Thank you!! :)
