### ISSUE TITLE
App Freeze when sideMenuController is not in hierarchy.

### ISSUE THREAD

**Issue by hackiftekhar** [dogo/AKSideMenu#71]
https://github.com/dogo/AKSideMenu/issues/47 is the duplicate card that hasn't been fixed yet. I cannot reopen due to insufficient permission.

###### Include the following:
 - AKSideMenu version: `1.4.4`
 - Device OS version: `13.1`
 - Device Name: `iPhone 11 Pro Max (Simulator)`
 
###### Reproduction Steps
 1. Create a brand new Xcode project and add AKSideMenu library.
 2. Embed ViewController in NavigationController.
 3. call `self.sideMenuViewController` in `viewDidAppear`.

###### Expected Result
- If there are no side menu controller embedded then `self.sideMenuViewController` will return nil.

###### Actual Result
- `self.sideMenuViewController` call stuck in an infinite loop.

### Tell us what could be improved:
- When `iterator.parent` is `nil`, both if condition fails and while loop stuck in an infinite loop. There should be a `nil` validation of the `iterator` variable in `sideMenuViewController` var.

![Screenshot 2019-11-19 at 5 08 12 PM](https://user-images.githubusercontent.com/3831495/69144114-92d3bc00-0af0-11ea-8c39-c945a638cfb9.png)

**Comment by dogo** [comment]
Thanks for reporting this issue and providing useful information.
Please update to 1.4.5

**Comment by hackiftekhar** [comment]
Thanks @dogo for quick action on this.
