### ISSUE TITLE
iOS Deployment Target 13.3.1 AKSideMenu is not working

### ISSUE THREAD

**Issue by adnanafridi619** [dogo/AKSideMenu#72]
I use AKSideMenu in my project , Everything was working fine with iOS target 13.1.1 in my mobile but when I updated my mobile to  iOS 13.3.1 , application  is not  running in my mobile due to AKSideMenu .
Error Message
dyld: Library not loaded: @rpath/AKSideMenu.framework/AKSideMenu
  Referenced from: /private/var/containers/Bundle/Application/541410A0-7C92-493A-AD9B-947191EE28AA/SalesReport.app/SalesReport
	/private/var/containers/Bundle/Application/541410A0-7C92-493A-AD9B-947191EE28AA/SalesReport.app/Frameworks/AKSideMenu.framework/AKSideMenu: stat() failed with errno=1

**Comment by aheze** [comment]
Yeah, looks like an iOS 13.3.1 error. Hopefully Apple puts a fix soon...
Maybe check this out: https://github.com/Alamofire/Alamofire/issues/3051
