### ISSUE TITLE
Please add Swift Package Manager (SPM) support.

### ISSUE THREAD

**Issue by ioseng42** [dogo/AKSideMenu#76]
Great little library.  Would like to use again!
Please add Swift Package Manager support so I can easily integrate it into my current project.

**Comment by dogo** [comment]
Hi @ioseng42 , could you please test the develop branch?

**Comment by ioseng42** [comment]
Branch 'develop' appears to be working fine.  Thanks!

**Comment by dogo** [comment]
Great
