### ISSUE TITLE
Package Manager Fails

### ISSUE THREAD

**Issue by Quailcreek** [dogo/AKSideMenu#79]
<img width="729" alt="Screen Shot 2021-06-20 at 2 12 49 PM" src="https://user-images.githubusercontent.com/14036156/122688551-c34e7100-d1d1-11eb-9391-e2ef93e09160.png">

- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKSideMenu version: `1.4.5`
 - Device OS version: `14.5`
 - Device Name: `All`
 
###### Reproduction Steps
 1. Using Xcode 12.5
 2. Trying to install AKSideMenu using package manager
 3.

###### Actual Result
The install fails

**Comment by dogo** [comment]
Please Update to 1.4.6 @Quailcreek
